"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&kv@vz!cq1t@b@&l-n9k1y%#h(-qxdmf(%v%b@+&#u80y-i_+i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'blog.apps.BlogConfig',
    'users.apps.UsersConfig',
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [

                os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

#STATIC_URL = '/static/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = 'blog:home'

LOGIN_URL = 'login'
"""
Explanation: amra views e profile function er upore '@login_required' decorator dara condition diye 
diyesi je, profile route e jete hole age login kore nite hobe. ekhon jokhon amader database accessable 
kuno user site ti theke logout kore nibe nijeke, tokhon shavabikvabei take tar profile e punoray jete hole
notun kore abar login korte hobe. tai jokhon amra logout korar por punoray profile e jete chai, tokhon
decorator condition use korar karone django 'accounts/login' namok ekti LOGIN URL provide kore. ar tokhon 
amaderke settings e define kore dite hoy je, LOGIN URL ti amaderke shuja login route/page e niye jabe. onno
kothay, '@login_required' decorator use korle eti lage. tai amaderke ei settings ti diye dite hobe. That's it!
"""

MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # BASE_DIR means project's base directoey.
MEDIA_URL = '/media/'
"""
Explanation: MEDIA ROOT is where our uploaded files('uploaded_pics' in this case) will be located
on the file system/base directory. Whereas MEDIA URL is basically how we'll access our media(eg.
an image) to the browser or to be more precise, 'The public url of that directory'(like: /media
/profile_pics/the source/url of that image.)
"""

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "arafathossain45621@gmail.com" #EMAIL_HOST_USER = "you@gmail.com"
EMAIL_HOST_PASSWORD = "qnad eseh hitb wszn"
# EMAIL_HOST_PASSWORD - "get it from gmail app password after setting 2 factor gmail authentication"

# Firstly, active two factor gmail authentication from here: 'https://www.google.com/landing/2step/'
# Then get your app password from here: 'https://myaccount.google.com/apppasswords'